<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Dsh.App\Dsh.App.csproj" />
    <ProjectReference Include="..\Dsh.Contract\Dsh.Contract.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="ZstdNet" Version="1.5.7" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>Dsh.Viewer</RootNamespace>
    <AssemblyName>Dsh.Viewer</AssemblyName>
  </PropertyGroup>

</Project>
